In [6]:
import pandas as pd
import numpy as np

In [7]:
import warnings
warnings.filterwarnings("ignore", category=RuntimeWarning)

In [8]:
df = pd.read_csv("adult2.csv")

In [9]:
df.columns = ['age', 
'workclass', 
'fnlwgt', 
'education', 
'education_num', 
'marital_status',
'occupation',
'relationship', 
'race', 
'sex',
'capital_gain', 
'capital_loss',
'hours_per_week', 
'native_country',
'salary']

In [10]:
df.isin(["?"]).sum(axis=0)

age                  0
workclass         2799
fnlwgt               0
education            0
education_num        0
marital_status       0
occupation        2809
relationship         0
race                 0
sex                  0
capital_gain         0
capital_loss         0
hours_per_week       0
native_country     857
salary               0
dtype: int64

In [11]:
df['native_country'] = df['native_country'].replace('?',np.nan)
df['workclass'] = df['workclass'].replace('?',np.nan)
df['occupation'] = df['occupation'].replace('?',np.nan)
#dropping the NaN rows now 
df.dropna(how='any',inplace=True)

In [12]:
df.isin(["?"]).sum(axis=0)

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
salary            0
dtype: int64

In [13]:
df = df.dropna()

In [14]:
len(df)

45222

In [15]:
print(df.isnull().sum())

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
salary            0
dtype: int64


In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45222 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             45222 non-null  int64 
 1   workclass       45222 non-null  object
 2   fnlwgt          45222 non-null  int64 
 3   education       45222 non-null  object
 4   education_num   45222 non-null  int64 
 5   marital_status  45222 non-null  object
 6   occupation      45222 non-null  object
 7   relationship    45222 non-null  object
 8   race            45222 non-null  object
 9   sex             45222 non-null  object
 10  capital_gain    45222 non-null  int64 
 11  capital_loss    45222 non-null  int64 
 12  hours_per_week  45222 non-null  int64 
 13  native_country  45222 non-null  object
 14  salary          45222 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.5+ MB


In [17]:
df.head()

age  workclass  fnlwgt     education  education_num      marital_status  \
0   25    Private  226802          11th              7       Never-married   
1   38    Private   89814       HS-grad              9  Married-civ-spouse   
2   28  Local-gov  336951    Assoc-acdm             12  Married-civ-spouse   
3   44    Private  160323  Some-college             10  Married-civ-spouse   
5   34    Private  198693          10th              6       Never-married   

          occupation   relationship   race   sex  capital_gain  capital_loss  \
0  Machine-op-inspct      Own-child  Black  Male             0             0   
1    Farming-fishing        Husband  White  Male             0             0   
2    Protective-serv        Husband  White  Male             0             0   
3  Machine-op-inspct        Husband  Black  Male          7688             0   
5      Other-service  Not-in-family  White  Male             0             0   

   hours_per_week native_country salary  
0              40  United-States  <=50K  
1              50  United-States  <=50K  
2              40  United-States   >50K  
3              40  United-States   >50K  
5              30  United-States  <=50K

In [18]:
print(df.workclass.unique())
print(df.education.unique())
print(df.marital_status.unique())
print(df.occupation.unique())
print(df.relationship.unique())
print(df.race.unique())
print(df.sex.unique())
print(df.native_country.unique())
print(df.salary.unique())

['Private' 'Local-gov' 'Self-emp-not-inc' 'Federal-gov' 'State-gov'
 'Self-emp-inc' 'Without-pay']
['11th' 'HS-grad' 'Assoc-acdm' 'Some-college' '10th' 'Prof-school'
 '7th-8th' 'Bachelors' 'Masters' '5th-6th' 'Assoc-voc' '9th' 'Doctorate'
 '12th' '1st-4th' 'Preschool']
['Never-married' 'Married-civ-spouse' 'Widowed' 'Separated' 'Divorced'
 'Married-spouse-absent' 'Married-AF-spouse']
['Machine-op-inspct' 'Farming-fishing' 'Protective-serv' 'Other-service'
 'Prof-specialty' 'Craft-repair' 'Adm-clerical' 'Exec-managerial'
 'Tech-support' 'Sales' 'Priv-house-serv' 'Transport-moving'
 'Handlers-cleaners' 'Armed-Forces']
['Own-child' 'Husband' 'Not-in-family' 'Unmarried' 'Wife' 'Other-relative']
['Black' 'White' 'Other' 'Amer-Indian-Eskimo' 'Asian-Pac-Islander']
['Male' 'Female']
['United-States' 'Peru' 'Guatemala' 'Mexico' 'Dominican-Republic'
 'Ireland' 'Germany' 'Philippines' 'Thailand' 'Haiti' 'El-Salvador'
 'Puerto-Rico' 'Vietnam' 'South' 'Columbia' 'Japan' 'India' 'Cambodia'
 'Poland'

In [19]:
#gender
df['sex'] = df['sex'].map({"Male": 0, "Female": 1})
#race
df['race'] = df['race'].map({'Black': 0, 'Asian-Pac-Islander': 1,'Other': 2, 'White': 3, 'Amer-Indian-Eskimo': 4})
#marital
df['marital_status'] = df['marital_status'].map({'Married-spouse-absent': 0, 'Widowed': 1, 'Married-civ-spouse': 2, 'Separated': 3, 'Divorced': 4,'Never-married': 5, 'Married-AF-spouse': 6})
#workclass
df['workclass'] = df['workclass'].map({'Self-emp-inc': 0, 'State-gov': 1,'Federal-gov': 2, 'Without-pay': 3, 'Local-gov': 4,'Private': 5, 'Self-emp-not-inc': 6})
#education
df['education'] = df['education'].map({'Some-college': 0, 'Preschool': 1, '5th-6th': 2, 'HS-grad': 3, 'Masters': 4, '12th': 5, '7th-8th': 6, 'Prof-school': 7,'1st-4th': 8, 'Assoc-acdm': 9, 'Doctorate': 10, '11th': 11,'Bachelors': 12, '10th': 13,'Assoc-voc': 14,'9th': 15})
#occupation
df['occupation'] = df['occupation'].map({ 'Farming-fishing': 1, 'Tech-support': 2, 'Adm-clerical': 3, 'Handlers-cleaners': 4, 'Prof-specialty': 5,'Machine-op-inspct': 6, 'Exec-managerial': 7,'Priv-house-serv': 8,'Craft-repair': 9,'Sales': 10, 'Transport-moving': 11, 'Armed-Forces': 12, 'Other-service': 13,'Protective-serv':14})
#relationship
df['relationship'] = df['relationship'].map({'Not-in-family': 0, 'Wife': 1, 'Other-relative': 2, 'Unmarried': 3,'Husband': 4,'Own-child': 5})
#salary
df['salary'] = df['salary'].map({'<=50K' : 0, '>50K' : 1})
#native_country
df.native_country = df.native_country.astype('category').cat.codes.astype('int64')


In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45222 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             45222 non-null  int64
 1   workclass       45222 non-null  int64
 2   fnlwgt          45222 non-null  int64
 3   education       45222 non-null  int64
 4   education_num   45222 non-null  int64
 5   marital_status  45222 non-null  int64
 6   occupation      45222 non-null  int64
 7   relationship    45222 non-null  int64
 8   race            45222 non-null  int64
 9   sex             45222 non-null  int64
 10  capital_gain    45222 non-null  int64
 11  capital_loss    45222 non-null  int64
 12  hours_per_week  45222 non-null  int64
 13  native_country  45222 non-null  int64
 14  salary          45222 non-null  int64
dtypes: int64(15)
memory usage: 5.5 MB


In [21]:
df

age  workclass  fnlwgt  education  education_num  marital_status  \
0       25          5  226802         11              7               5   
1       38          5   89814          3              9               2   
2       28          4  336951          9             12               2   
3       44          5  160323          0             10               2   
5       34          5  198693         13              6               5   
...    ...        ...     ...        ...            ...             ...   
48837   27          5  257302          9             12               2   
48838   40          5  154374          3              9               2   
48839   58          5  151910          3              9               1   
48840   22          5  201490          3              9               5   
48841   52          0  287927          3              9               2   

       occupation  relationship  race  sex  capital_gain  capital_loss  \
0               6             5     0    0             0             0   
1               1             4     3    0             0             0   
2              14             4     3    0             0             0   
3               6             4     0    0          7688             0   
5              13             0     3    0             0             0   
...           ...           ...   ...  ...           ...           ...   
48837           2             1     3    1             0             0   
48838           6             4     3    0             0             0   
48839           3             3     3    1             0             0   
48840           3             5     3    0             0             0   
48841           7             1     3    1         15024             0   

       hours_per_week  native_country  salary  
0                  40              38       0  
1                  50              38       0  
2                  40              38       1  
3                  40              38       1  
5                  30              38       0  
...               ...             ...     ...  
48837              38              38       0  
48838              40              38       1  
48839              40              38       0  
48840              20              38       0  
48841              40              38       1  

[45222 rows x 15 columns]

In [22]:
print(df.workclass.unique(), len(df.workclass.unique()))
print(df.education.unique(), len(df.education.unique()))
print(df.marital_status.unique(), len(df.marital_status.unique()))
print(df.occupation.unique(), len(df.occupation.unique()))
print(df.relationship.unique(), len(df.relationship.unique()))
print(df.race.unique(), len(df.race.unique()))
print(df.sex.unique(), len(df.sex.unique()))
print(df.native_country.unique(), len(df.native_country.unique()))
print(df.salary.unique())

[5 4 6 2 1 0 3] 7
[11  3  9  0 13  7  6 12  4  2 14 15 10  5  8  1] 16
[5 2 1 3 4 0 6] 7
[ 6  1 14 13  5  9  3  7  2 10  8 11  4 12] 14
[5 4 0 3 1 2] 6
[0 3 2 4 1] 5
[0 1] 2
[38 28 12 25  5 20 10 29 36 13  7 32 39 34  3 23 18  0 30 24  8  4 35 21
  1 31  2 26 15 19 33 22  6 40 17 16 11 37 27  9 14] 41
[0 1]


In [23]:
X = df.values[:, 0:14]
Y = df.values[:,14]

In [24]:
X

array([[    25,      5, 226802, ...,      0,     40,     38],
       [    38,      5,  89814, ...,      0,     50,     38],
       [    28,      4, 336951, ...,      0,     40,     38],
       ...,
       [    58,      5, 151910, ...,      0,     40,     38],
       [    22,      5, 201490, ...,      0,     20,     38],
       [    52,      0, 287927, ...,      0,     40,     38]])

In [25]:
Y

array([0, 0, 1, ..., 0, 0, 1])

In [26]:
def train_test_split(X, y, seed):
        np.random.seed(seed)
        p = np.random.permutation(X.shape[0])
        X = X[p,:]
        y = y[p]

        m = X.shape[0]
        print("total rows: ", m)
        training_size = int(m *0.67)

        X_train = X[:training_size, :]
        X_test = X[ training_size:, :]

        y_train = y[:training_size]
        y_test = y[training_size:]

        return X_train, X_test, y_train, y_test

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, 23)
print("x train: ", len(X_train))
print("x test:  ", len(X_test))
print("y train: ", len(y_train))
print("y test:  ", len(y_test))

total rows:  45222
x train:  30298
x test:   14924
y train:  30298
y test:   14924


In [28]:
print((X_train))
print((X_test))
print((y_train))
print((y_test))

[[    24      5 373628 ...   1504     40     38]
 [    43      4 323627 ...      0     12     38]
 [    21      5 189749 ...      0     40     38]
 ...
 [    52      5 180142 ...      0     45     38]
 [    35      5 172845 ...      0     30     38]
 [    58      4  34878 ...      0     50     38]]
[[    29      0 206903 ...      0     55     38]
 [    37      1 172425 ...      0     40     38]
 [    20      5 347530 ...      0     25     38]
 ...
 [    23      5 213955 ...   2001     40     38]
 [    63      5 195338 ...      0     45     38]
 [    38      5 167440 ...      0     40     38]]
[0 0 0 ... 0 0 0]
[1 0 0 ... 0 1 0]


In [29]:
class NaiveBayesClassifier:
    def fit(self, X_train, y_train):
        # Calculate the prior probability of each class
        self.classes, counts = np.unique(y_train, return_counts=True)
        self.prior_probs = counts / len(y_train)
        
        # Calculate the conditional probability of each feature given each class
        self.cond_probs = {}
        for c in self.classes:
            X_c = X_train[y_train == c]
            self.cond_probs[c] = {
                "mean": np.mean(X_c, axis=0),
                "std": np.std(X_c, axis=0) + 1e-8  # Added  small epsilon to avoid division by zero
            }
    def predict(self, X_test):
        # Step 3: Predict the class
        y_pred = []
        for x in X_test:
            probs = []
            for c in self.classes:
                prior_prob = np.log(self.prior_probs[c])
                cond_prob = np.sum(np.log(self._gaussian_pdf(x, self.cond_probs[c]["mean"], self.cond_probs[c]["std"])))
                probs.append(prior_prob + cond_prob)
            y_pred.append(self.classes[np.argmax(probs)])
        return np.array(y_pred)
    
    def _gaussian_pdf(self, x, mean, std):
        # Gaussian Probability Density Function (PDF)
        exponent = -0.5 * ((x - mean) / std) ** 2
        return (1 / (np.sqrt(2 * np.pi) * std)) * np.exp(exponent)

    def accuracy(self, X_test, y_test):
        y_pred = self.predict(X_test)
        accuracy = np.mean(y_pred == y_test)
        return accuracy
    def evaluate(self, X_test, y_test):
        y_pred = self.predict(X_test)
        
        # Calculate accuracy
        accuracy = np.mean(y_pred == y_test)
        
        # Calculate precision, recall, and F1-score
        tp = np.sum((y_pred == 1) & (y_test == 1))
        fp = np.sum((y_pred == 1) & (y_test == 0))
        fn = np.sum((y_pred == 0) & (y_test == 1))
        
        precision = tp / (tp + fp + 1e-8)  # Add small epsilon to avoid division by zero
        recall = tp / (tp + fn + 1e-8)
        f1_score = 2 * (precision * recall) / (precision + recall + 1e-8)
        
        print("accuracy: ", accuracy)
        print("precision: ", precision)
        print("recall: ", recall)
        print("F1 score: ", f1_score)
        
        return accuracy, precision, recall, f1_score

In [30]:
classifier = NaiveBayesClassifier()
classifier.fit(X_train, y_train)

In [31]:
print(classifier.prior_probs)

[0.75292098 0.24707902]


In [32]:
print(classifier.cond_probs)

{0: {'mean': array([3.68067684e+01, 4.66162546e+00, 1.89795671e+05, 5.23750658e+00,
       9.63207961e+00, 3.53160617e+00, 7.40838155e+00, 2.65268280e+00,
       2.61134491e+00, 3.81948097e-01, 1.49899614e+02, 5.38385499e+01,
       3.94081624e+01, 3.63446432e+01]), 'std': array([1.36240063e+01, 1.21506211e+00, 1.05714750e+05, 4.83997466e+00,
       2.40769491e+00, 1.45467817e+00, 3.67984687e+00, 1.96973425e+00,
       9.93230294e-01, 4.85863930e-01, 8.94809866e+02, 3.10591657e+02,
       1.20503223e+01, 6.11800355e+00])}, 1: {'mean': array([4.40444830e+01, 4.26355864e+00, 1.88789406e+05, 6.49559177e+00,
       1.15849586e+01, 2.30390061e+00, 6.98771039e+00, 3.26075341e+00,
       2.78840502e+00, 1.48543949e-01, 4.00458776e+03, 1.85800027e+02,
       4.56912904e+01, 3.65968474e+01]), 'std': array([1.04123390e+01, 1.70558789e+00, 1.02795626e+05, 4.82904865e+00,
       2.37386773e+00, 8.85935632e-01, 2.81044362e+00, 1.44296730e+00,
       7.30141279e-01, 3.55638371e-01, 1.47361809e+04, 5

In [33]:
classifier.predict(X_test)


array([1, 0, 0, ..., 1, 1, 1])

In [34]:
classifier.accuracy(X_test,y_test)

0.8047440364513535

In [35]:
classifier.evaluate(X_test, y_test)

accuracy:  0.8047440364513535
precision:  0.6887850467257534
recall:  0.3960236432015153
F1 score:  0.502900029480492


(0.8047440364513535, 0.6887850467257534, 0.3960236432015153, 0.502900029480492)

In [36]:
seeds = np.random.randint(10000, size=50)
accuracy = []
precision = []
recall = []
F1_score =[]
for i in range(0,50):
    print(seeds[i])
    X_train, X_test, y_train, y_test = train_test_split(X, Y, seeds[i])
    classifier = NaiveBayesClassifier()
    classifier.fit(X_train, y_train)
    classifier.predict(X_test)
    acc,pre,rec,f1 = classifier.evaluate(X_test, y_test)
    accuracy.append(acc)
    precision.append(pre)
    recall.append(rec)
    F1_score.append(f1)
    
        

3260
total rows:  45222
accuracy:  0.8066872152238006
precision:  0.6864127879610418
recall:  0.39695486677434216
F1 score:  0.5030146379047283
5407
total rows:  45222
accuracy:  0.8042079871348164
precision:  0.6805096743714936
recall:  0.39110387849093814
F1 score:  0.4967275186147741
87
total rows:  45222
accuracy:  0.8092334494773519
precision:  0.6790588235262163
recall:  0.39994456762638597
F1 score:  0.5034013558770327
4338
total rows:  45222
accuracy:  0.8090324309836505
precision:  0.6733271375433396
recall:  0.40294771968742227
F1 score:  0.5041753606582654
6935
total rows:  45222
accuracy:  0.8060171535781292
precision:  0.6939916162054309
recall:  0.39967811158691074
F1 score:  0.507234037913556
2625
total rows:  45222
accuracy:  0.8058161350844277
precision:  0.6807909604487722
recall:  0.3944353518810845
F1 score:  0.4994818606378839
2326
total rows:  45222
accuracy:  0.8037389439828464
precision:  0.6915446386363178
recall:  0.39144385026633305
F1 score:  0.4999146274464

In [37]:
print("Mean accuracy of 10 random splits:         ", np.mean(accuracy))
print("Variance of accuracy of 10 random splits:  ", np.var(accuracy))
print("---------------------------------------------------------------------")
print("Mean precision of 10 random splits:        ", np.mean(precision))
print("Variance of precision of 10 random splits: ", np.var(precision))
print("---------------------------------------------------------------------")
print("Mean recall of 10 random splits:           ", np.mean(recall))
print("Variance of recall of 10 random splits:    ", np.var(recall))
print("---------------------------------------------------------------------")
print("Mean F1 score of 10 random splits:         ", np.mean(F1_score))
print("Variance of F1 score of 10 random splits:  ", np.var(F1_score))


Mean accuracy of 10 random splits:          0.8048298043419995
Variance of accuracy of 10 random splits:   8.347312257203689e-06
---------------------------------------------------------------------
Mean precision of 10 random splits:         0.6824445673624742
Variance of precision of 10 random splits:  8.307107490703945e-05
---------------------------------------------------------------------
Mean recall of 10 random splits:            0.3943953858570691
Variance of recall of 10 random splits:     5.87031225776204e-05
---------------------------------------------------------------------
Mean F1 score of 10 random splits:          0.4998477889430431
Variance of F1 score of 10 random splits:   5.362271465673041e-05


In [48]:
from sklearn.neighbors import KNeighborsClassifier
seeds = np.random.randint(10000, size=50)
accuracy6 = []
precision6 = []
recall6 = []
F1_score6 =[]
for i in range(0,50):
    print(seeds[i])
    X_train, X_test, y_train, y_test = train_test_split(X, Y, seeds[i])
    clf = KNeighborsClassifier(n_neighbors=5)
    classifier.fit(X_train, y_train)
    classifier.predict(X_test)
    acc,pre,rec,f1 = classifier.evaluate(X_test, y_test)
    accuracy6.append(acc)
    precision6.append(pre)
    recall6.append(rec)
    F1_score6.append(f1)

244
total rows:  45222
accuracy:  0.8000536049316537
precision:  0.6542577943198965
recall:  0.38552234713357414
F1 score:  0.4851621761466734
6325
total rows:  45222
accuracy:  0.8062851782363978
precision:  0.6802594995334558
recall:  0.400109021530662
F1 score:  0.5038613304983716
5904
total rows:  45222
accuracy:  0.8016617528812651
precision:  0.6783054003692817
recall:  0.39103596349868214
F1 score:  0.49608443526381685
2358
total rows:  45222
accuracy:  0.8072902707049049
precision:  0.6900232018529465
recall:  0.4024357239501964
F1 score:  0.5083760637208276
1939
total rows:  45222
accuracy:  0.8019967837041008
precision:  0.6808109382334709
recall:  0.38796346050406244
F1 score:  0.4942666392210355
385
total rows:  45222
accuracy:  0.8007236665773251
precision:  0.681390977440407
recall:  0.38707955152058976
F1 score:  0.493701050876494
1626
total rows:  45222
accuracy:  0.8086974001608148
precision:  0.6846081208655118
recall:  0.3986802309584859
F1 score:  0.5039096391345925

In [49]:
print("Mean accuracy of 10 random splits:         ", np.mean(accuracy6))
print("Variance of accuracy of 10 random splits:  ", np.var(accuracy6))
print("---------------------------------------------------------------------")
print("Mean precision of 10 random splits:        ", np.mean(precision6))
print("Variance of precision of 10 random splits: ", np.var(precision6))
print("---------------------------------------------------------------------")
print("Mean recall of 10 random splits:           ", np.mean(recall6))
print("Variance of recall of 10 random splits:    ", np.var(recall6))
print("---------------------------------------------------------------------")
print("Mean F1 score of 10 random splits:         ", np.mean(F1_score6))
print("Variance of F1 score of 10 random splits:  ", np.var(F1_score6))

Mean accuracy of 10 random splits:          0.8043781827928168
Variance of accuracy of 10 random splits:   1.4163283911961837e-05
---------------------------------------------------------------------
Mean precision of 10 random splits:         0.6824189591754943
Variance of precision of 10 random splits:  0.0001812939426058734
---------------------------------------------------------------------
Mean recall of 10 random splits:            0.3937001170708638
Variance of recall of 10 random splits:     8.295969160529635e-05
---------------------------------------------------------------------
Mean F1 score of 10 random splits:          0.4992906031714272
Variance of F1 score of 10 random splits:   0.00010110274024584125


In [50]:
from sklearn.linear_model import LogisticRegression
seeds = np.random.randint(10000, size=50)
accuracy7 = []
precision7 = []
recall7 = []
F1_score7 =[]
for i in range(0,50):
    print(seeds[i])
    X_train, X_test, y_train, y_test = train_test_split(X, Y, seeds[i])
    clf = KNeighborsClassifier(n_neighbors=5)
    classifier.fit(X_train, y_train)
    classifier.predict(X_test)
    acc,pre,rec,f1 = classifier.evaluate(X_test, y_test)
    accuracy7.append(acc)
    precision7.append(pre)
    recall7.append(rec)
    F1_score7.append(f1)

2644
total rows:  45222
accuracy:  0.7999195926025194
precision:  0.67697277341635
recall:  0.39088729016682416
F1 score:  0.49560810346530043
1254
total rows:  45222
accuracy:  0.8038729563119807
precision:  0.6780055917955359
recall:  0.39420211324737414
F1 score:  0.4985437678344639
47
total rows:  45222
accuracy:  0.8034709193245778
precision:  0.6682330827036268
recall:  0.3896958070693623
F1 score:  0.4922970353310439
4748
total rows:  45222
accuracy:  0.802599839185205
precision:  0.6688402421953012
recall:  0.3911740670106479
F1 score:  0.4936404216047017
3828
total rows:  45222
accuracy:  0.8055481104261593
precision:  0.6788425047406127
recall:  0.3914113785547281
F1 score:  0.496530182728791
6833
total rows:  45222
accuracy:  0.8014607343875637
precision:  0.6755617977496463
recall:  0.388634527335339
F1 score:  0.49341767359738004
3635
total rows:  45222
accuracy:  0.8034709193245778
precision:  0.6782650142960999
recall:  0.38657973376694765
F1 score:  0.4924727415233173
7

In [51]:
print("Mean accuracy of 10 random splits:         ", np.mean(accuracy7))
print("Variance of accuracy of 10 random splits:  ", np.var(accuracy7))
print("---------------------------------------------------------------------")
print("Mean precision of 10 random splits:        ", np.mean(precision7))
print("Variance of precision of 10 random splits: ", np.var(precision7))
print("---------------------------------------------------------------------")
print("Mean recall of 10 random splits:           ", np.mean(recall7))
print("Variance of recall of 10 random splits:    ", np.var(recall7))
print("---------------------------------------------------------------------")
print("Mean F1 score of 10 random splits:         ", np.mean(F1_score7))
print("Variance of F1 score of 10 random splits:  ", np.var(F1_score7))

Mean accuracy of 10 random splits:          0.8045523988206915
Variance of accuracy of 10 random splits:   6.926905487580389e-06
---------------------------------------------------------------------
Mean precision of 10 random splits:         0.683313609107818
Variance of precision of 10 random splits:  9.390604355393313e-05
---------------------------------------------------------------------
Mean recall of 10 random splits:            0.394374046311737
Variance of recall of 10 random splits:     4.819468533519341e-05
---------------------------------------------------------------------
Mean F1 score of 10 random splits:          0.5000848504229466
Variance of F1 score of 10 random splits:   5.491832429010143e-05


In [55]:
class NaiveBayesClassifier2:
    def __init__(self, alpha=1.0):
        self.alpha = alpha  # Smoothing parameter
    def fit(self, X_train, y_train):
        # Calculate the prior probability of each class
        self.classes, counts = np.unique(y_train, return_counts=True)
        self.prior_probs = (counts + 1)/ (len(y_train)+2)
        
        # Calculate the conditional probability of each feature given each class
        self.cond_probs = {}
        for c in self.classes:
            X_c = X_train[y_train == c]
            self.cond_probs[c] = {
                "mean": np.mean(X_c, axis=0),
                "std": np.std(X_c, axis=0)
            }
    def predict(self, X_test):
        # Step 3: Predict the class
        y_pred = []
        for x in X_test:
            probs = []
            for c in self.classes:
                prior_prob = np.log(self.prior_probs[c])
                cond_prob = np.sum(np.log(self._gaussian_pdf(x, self.cond_probs[c]["mean"], self.cond_probs[c]["std"])))
                probs.append(prior_prob + cond_prob)
            y_pred.append(self.classes[np.argmax(probs)])
        return np.array(y_pred)
    
    def _gaussian_pdf(self, x, mean, std):
        # Gaussian Probability Density Function (PDF)
        exponent = -0.5 * ((x - mean) / std) ** 2
        return (1 / (np.sqrt(2 * np.pi) * std)) * np.exp(exponent)

    def accuracy(self, X_test, y_test):
        y_pred = self.predict(X_test)
        accuracy = np.mean(y_pred == y_test)
        return accuracy
    def evaluate(self, X_test, y_test):
        y_pred = self.predict(X_test)
        
        # Calculate accuracy
        accuracy = np.mean(y_pred == y_test)
        
        # Calculate precision, recall, and F1-score
        tp = np.sum((y_pred == 1) & (y_test == 1))
        fp = np.sum((y_pred == 1) & (y_test == 0))
        fn = np.sum((y_pred == 0) & (y_test == 1))
        
        precision = tp / (tp + fp + 1e-8)  # Add small epsilon to avoid division by zero
        recall = tp / (tp + fn + 1e-8)
        f1_score = 2 * (precision * recall) / (precision + recall + 1e-8)
        
        print("accuracy: ", accuracy)
        print("precision: ", precision)
        print("recall: ", recall)
        print("F1 score: ", f1_score)
        
        return accuracy, precision, recall, f1_score

In [56]:
seeds = np.random.randint(10000, size=50)
accuracy2 = []
precision2 = []
recall2 = []
F1_score2 =[]
for i in range(0,50):
    print(seeds[i])
    X_train, X_test, y_train, y_test = train_test_split(X, Y, seeds[i])
    classifier = NaiveBayesClassifier2()
    classifier.fit(X_train, y_train)
    classifier.predict(X_test)
    acc,pre,rec,f1 = classifier.evaluate(X_test, y_test)
    accuracy2.append(acc)
    precision2.append(pre)
    recall2.append(rec)
    F1_score2.append(f1)
    
        

5936
total rows:  45222
accuracy:  0.8114446529080676
precision:  0.6916548797704307
recall:  0.40446650123957967
F1 score:  0.5104384087026241
2953
total rows:  45222
accuracy:  0.8080943446797105
precision:  0.6749654218502769
recall:  0.40408501241953054
F1 score:  0.5055248571918027
4910
total rows:  45222
accuracy:  0.7996515679442509
precision:  0.6629966491112351
recall:  0.3772813947143087
F1 score:  0.48090277315327884
8162
total rows:  45222
accuracy:  0.8043419994639507
precision:  0.6876181474447656
recall:  0.39176090468392094
F1 score:  0.4991423624408357
1096
total rows:  45222
accuracy:  0.8029348700080408
precision:  0.6637002341889289
recall:  0.3892857142846448
F1 score:  0.4907359260738089
536
total rows:  45222
accuracy:  0.8044090056285178
precision:  0.69134615384283
recall:  0.3870794078051492
F1 score:  0.4962899004868969
1991
total rows:  45222
accuracy:  0.8046770302867864
precision:  0.689102564099409
recall:  0.4022988505736373
F1 score:  0.5080168729806954

In [57]:
print("Mean accuracy of 10 random splits:         ", np.mean(accuracy2))
print("Variance of accuracy of 10 random splits:  ", np.var(accuracy2))
print("---------------------------------------------------------------------")
print("Mean precision of 10 random splits:        ", np.mean(precision2))
print("Variance of precision of 10 random splits: ", np.var(precision2))
print("---------------------------------------------------------------------")
print("Mean recall of 10 random splits:           ", np.mean(recall2))
print("Variance of recall of 10 random splits:    ", np.var(recall2))
print("---------------------------------------------------------------------")
print("Mean F1 score of 10 random splits:         ", np.mean(F1_score2))
print("Variance of F1 score of 10 random splits:  ", np.var(F1_score2))

Mean accuracy of 10 random splits:          0.8043326186009111
Variance of accuracy of 10 random splits:   8.459193335575158e-06
---------------------------------------------------------------------
Mean precision of 10 random splits:         0.6792004349045978
Variance of precision of 10 random splits:  7.747448361160017e-05
---------------------------------------------------------------------
Mean recall of 10 random splits:            0.3934081522121135
Variance of recall of 10 random splits:     4.891977115048165e-05
---------------------------------------------------------------------
Mean F1 score of 10 random splits:          0.4982052061005867
Variance of F1 score of 10 random splits:   5.2650793201349166e-05


In [59]:
class NaiveBayesClassifier2:
    def __init__(self, alpha=1.0):
        self.alpha = alpha  # Smoothing parameter
    def fit(self, X_train, y_train):
        # Calculate the prior probability of each class
        self.classes, counts = np.unique(y_train, return_counts=True)
        self.prior_probs = (counts + 5000)/ (len(y_train)+200)
        
        # Calculate the conditional probability of each feature given each class
        self.cond_probs = {}
        for c in self.classes:
            X_c = X_train[y_train == c]
            self.cond_probs[c] = {
                "mean": np.mean(X_c, axis=0),
                "std": np.std(X_c, axis=0)
            }
    def predict(self, X_test):
        # Step 3: Predict the class
        y_pred = []
        for x in X_test:
            probs = []
            for c in self.classes:
                prior_prob = np.log(self.prior_probs[c])
                cond_prob = np.sum(np.log(self._gaussian_pdf(x, self.cond_probs[c]["mean"], self.cond_probs[c]["std"])))
                probs.append(prior_prob + cond_prob)
            y_pred.append(self.classes[np.argmax(probs)])
        return np.array(y_pred)
    
    def _gaussian_pdf(self, x, mean, std):
        # Gaussian Probability Density Function (PDF)
        exponent = -0.5 * ((x - mean) / std) ** 2
        return (1 / (np.sqrt(2 * np.pi) * std)) * np.exp(exponent)

    def accuracy(self, X_test, y_test):
        y_pred = self.predict(X_test)
        accuracy = np.mean(y_pred == y_test)
        return accuracy
    def evaluate(self, X_test, y_test):
        y_pred = self.predict(X_test)
        
        # Calculate accuracy
        accuracy = np.mean(y_pred == y_test)
        
        # Calculate precision, recall, and F1-score
        tp = np.sum((y_pred == 1) & (y_test == 1))
        fp = np.sum((y_pred == 1) & (y_test == 0))
        fn = np.sum((y_pred == 0) & (y_test == 1))
        
        precision = tp / (tp + fp + 1e-8)  # Add small epsilon to avoid division by zero
        recall = tp / (tp + fn + 1e-8)
        f1_score = 2 * (precision * recall) / (precision + recall + 1e-8)
        
        print("accuracy: ", accuracy)
        print("precision: ", precision)
        print("recall: ", recall)
        print("F1 score: ", f1_score)
        
        return accuracy, precision, recall, f1_score

seeds = np.random.randint(10000, size=50)
accuracy2 = []
precision2 = []
recall2 = []
F1_score2 =[]
for i in range(0,50):
    print(seeds[i])
    X_train, X_test, y_train, y_test = train_test_split(X, Y, seeds[i])
    classifier = NaiveBayesClassifier2()
    classifier.fit(X_train, y_train)
    classifier.predict(X_test)
    acc,pre,rec,f1 = classifier.evaluate(X_test, y_test)
    accuracy2.append(acc)
    precision2.append(pre)
    recall2.append(rec)
    F1_score2.append(f1)
    

print("Mean accuracy of 10 random splits:         ", np.mean(accuracy2))
print("Variance of accuracy of 10 random splits:  ", np.var(accuracy2))
print("---------------------------------------------------------------------")
print("Mean precision of 10 random splits:        ", np.mean(precision2))
print("Variance of precision of 10 random splits: ", np.var(precision2))
print("---------------------------------------------------------------------")
print("Mean recall of 10 random splits:           ", np.mean(recall2))
print("Variance of recall of 10 random splits:    ", np.var(recall2))
print("---------------------------------------------------------------------")
print("Mean F1 score of 10 random splits:         ", np.mean(F1_score2))
print("Variance of F1 score of 10 random splits:  ", np.var(F1_score2))

2417
total rows:  45222
accuracy:  0.808295363173412
precision:  0.6875834445897304
recall:  0.4171166306684203
F1 score:  0.5192404590855693
6614
total rows:  45222
accuracy:  0.8070222460466363
precision:  0.6823940585378664
recall:  0.4204576043057323
F1 score:  0.5203197820891121
2626
total rows:  45222
accuracy:  0.8097024926293219
precision:  0.672842105260325
recall:  0.43649276153937044
F1 score:  0.5294897235220931
3413
total rows:  45222
accuracy:  0.8092334494773519
precision:  0.672451193055651
recall:  0.42559033497961124
F1 score:  0.5212712244421543
7761
total rows:  45222
accuracy:  0.8022648083623694
precision:  0.6605543709993154
recall:  0.4181965442753289
F1 score:  0.5121507639727819
8320
total rows:  45222
accuracy:  0.8110426159206647
precision:  0.6849495392686049
recall:  0.42615342615226276
F1 score:  0.5254123143539694
933
total rows:  45222
accuracy:  0.8059501474135621
precision:  0.6656548135270354
recall:  0.41939890710267924
F1 score:  0.5145826301870899

In [61]:
class NaiveBayesClassifier2:
    def __init__(self, alpha=1.0):
        self.alpha = alpha  # Smoothing parameter
    def fit(self, X_train, y_train):
        # Calculate the prior probability of each class
        self.classes, counts = np.unique(y_train, return_counts=True)
        self.prior_probs = (counts )/ (len(y_train))
        
        # Calculate the conditional probability of each feature given each class
        self.cond_probs = {}
        for c in self.classes:
            X_c = X_train[y_train == c]
            self.cond_probs[c] = {
                "mean": np.mean(X_c, axis=0) + 1,
                "std": np.std(X_c, axis=0) + 2
            }
    def predict(self, X_test):
        # Step 3: Predict the class
        y_pred = []
        for x in X_test:
            probs = []
            for c in self.classes:
                prior_prob = np.log(self.prior_probs[c])
                cond_prob = np.sum(np.log(self._gaussian_pdf(x, self.cond_probs[c]["mean"], self.cond_probs[c]["std"])))
                probs.append(prior_prob + cond_prob)
            y_pred.append(self.classes[np.argmax(probs)])
        return np.array(y_pred)
    
    def _gaussian_pdf(self, x, mean, std):
        # Gaussian Probability Density Function (PDF)
        exponent = -0.5 * ((x - mean) / std) ** 2
        return (1 / (np.sqrt(2 * np.pi) * std)) * np.exp(exponent)

    def accuracy(self, X_test, y_test):
        y_pred = self.predict(X_test)
        accuracy = np.mean(y_pred == y_test)
        return accuracy
    def evaluate(self, X_test, y_test):
        y_pred = self.predict(X_test)
        
        # Calculate accuracy
        accuracy = np.mean(y_pred == y_test)
        
        # Calculate precision, recall, and F1-score
        tp = np.sum((y_pred == 1) & (y_test == 1))
        fp = np.sum((y_pred == 1) & (y_test == 0))
        fn = np.sum((y_pred == 0) & (y_test == 1))
        
        precision = tp / (tp + fp + 1e-8)  # Add small epsilon to avoid division by zero
        recall = tp / (tp + fn + 1e-8)
        f1_score = 2 * (precision * recall) / (precision + recall + 1e-8)
        
        print("accuracy: ", accuracy)
        print("precision: ", precision)
        print("recall: ", recall)
        print("F1 score: ", f1_score)
        
        return accuracy, precision, recall, f1_score

seeds = np.random.randint(10000, size=50)
accuracy2 = []
precision2 = []
recall2 = []
F1_score2 =[]
for i in range(0,50):
    print(seeds[i])
    X_train, X_test, y_train, y_test = train_test_split(X, Y, seeds[i])
    classifier = NaiveBayesClassifier2()
    classifier.fit(X_train, y_train)
    classifier.predict(X_test)
    acc,pre,rec,f1 = classifier.evaluate(X_test, y_test)
    accuracy2.append(acc)
    precision2.append(pre)
    recall2.append(rec)
    F1_score2.append(f1)
    

print("Mean accuracy of 10 random splits:         ", np.mean(accuracy2))
print("Variance of accuracy of 10 random splits:  ", np.var(accuracy2))
print("---------------------------------------------------------------------")
print("Mean precision of 10 random splits:        ", np.mean(precision2))
print("Variance of precision of 10 random splits: ", np.var(precision2))
print("---------------------------------------------------------------------")
print("Mean recall of 10 random splits:           ", np.mean(recall2))
print("Variance of recall of 10 random splits:    ", np.var(recall2))
print("---------------------------------------------------------------------")
print("Mean F1 score of 10 random splits:         ", np.mean(F1_score2))
print("Variance of F1 score of 10 random splits:  ", np.var(F1_score2))

6029
total rows:  45222
accuracy:  0.7900696864111498
precision:  0.6463484761319934
recall:  0.30862163646263424
F1 score:  0.41776621008207415
4232
total rows:  45222
accuracy:  0.793017957652104
precision:  0.6501116071392293
recall:  0.3212020953947582
F1 score:  0.42996862447006273
8139
total rows:  45222
accuracy:  0.7824309836504958
precision:  0.6401998889470284
recall:  0.30730277185419164
F1 score:  0.41527102028705787
4146
total rows:  45222
accuracy:  0.7856472795497186
precision:  0.650115473437355
recall:  0.302769561709323
F1 score:  0.4131352002124833
677
total rows:  45222
accuracy:  0.7867193781827928
precision:  0.6514124293748508
recall:  0.3100295778426727
F1 score:  0.4201129488079417
5282
total rows:  45222
accuracy:  0.7922138836772983
precision:  0.6605011933134816
recall:  0.304204451771629
F1 score:  0.4165569100736902
5761
total rows:  45222
accuracy:  0.7869874028410614
precision:  0.664788732390621
recall:  0.31349628055177076
F1 score:  0.4260696833124445